#Hermes Comercial - Configuração de Banco de Dados
#Sun Apr 26 18:58:00 BRT 2026
database.description=Banco de dados PostgreSQL local
database.name=hermescomercialdb
database.type=POSTGRESQL
database.host=localhost
database.port=5432
database.user=postgres
database.password=postgres123
