flyway.url=jdbc:postgresql://localhost:5432/hermescomercialdb
flyway.user=postgres
flyway.password=postgres
flyway.cleanDisabled=false
flyway.locations=classpath:db/migration
flyway.baselineOnMigrate=true