-- V1__create_comercialHermesDB.sql
-- Script de migração para o sistema PDV Hermes Comercial
-- Inclui tabelas para o sistema completo de Point of Sale
-- Data: 2024-04-17
-- Autor: Sistema Hermes Comercial

-- Tabelas básicas do sistema
CREATE TABLE USUARIO (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    TIPO_USUARIO VARCHAR(15) NOT NULL, -- CLIENTE, FUNCIONARIO, FORNECEDOR
    TIPO_PESSOA VARCHAR(1), -- F para Física, J para Jurídica
    CPF VARCHAR(14),
    RG VARCHAR(20),
    DATA_NASCIMENTO DATE,
    CNPJ VARCHAR(18),
    NOME_FANTASIA VARCHAR(100),
    INSCRICAO_ESTADUAL VARCHAR(20),
    ENDERECO VARCHAR(100),
    NUMERO VARCHAR(10),
    COMPLEMENTO VARCHAR(50),
    BAIRRO VARCHAR(50),
    CIDADE VARCHAR(50),
    ESTADO VARCHAR(2),
    CEP VARCHAR(10),
    TELEFONE VARCHAR(15),
    CELULAR VARCHAR(15),
    WHATSAPP VARCHAR(15),
    EMAIL VARCHAR(100),
    OBSERVACOES TEXT,
    ATIVO BOOLEAN DEFAULT TRUE,
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATA_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE GRUPO_IMPOSTOS(
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME_GRUPO VARCHAR(100),
    DESCRICAO VARCHAR(255),
    ATIVO BOOLEAN,
    DATA_CRIACAO VARCHAR(20)
);

CREATE TABLE PRODUTO (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME VARCHAR(50),
    CATEGORIA VARCHAR(50),
    SUBCATEGORIA VARCHAR(50),
    CODIGO VARCHAR(50),
    MARCA VARCHAR(50),
    CODIGO_BARRAS VARCHAR(20),
    PRECO_VENDA DECIMAL(10,2),
    PRECO_CUSTO DECIMAL(10,2),
    UNIDADE VARCHAR(10),
    ID_GRUPO_IMPOSTO INT,
    FOREIGN KEY (ID_GRUPO_IMPOSTO) REFERENCES GRUPO_IMPOSTOS(ID)
);

CREATE TABLE ESTOQUE (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FK_PRODUTO INTEGER,
    QUANTIDADE INTEGER,
    MAXIMO INTEGER,
    MINIMO INTEGER,
    FOREIGN KEY (FK_PRODUTO) REFERENCES PRODUTO(ID)
);

CREATE TABLE LOGIN (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FK_USUARIO INTEGER,
    LOGIN VARCHAR(50),
    SENHA VARCHAR(50),
    FOREIGN KEY (FK_USUARIO) REFERENCES USUARIO(ID)
);

CREATE TABLE IMPOSTO (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_GRUPO_IMPOSTO INT,
    ORIGEM_MERCADORIA FLOAT,
    CST_ICMS VARCHAR(10),
    CSOSN VARCHAR(10),
    ALIQUOTA_ICMS FLOAT,
    ALIQUOTA_COFINS FLOAT,
    ALIQUOTA_IPI FLOAT,
    ALIQUOTA_PIS FLOAT,
    CFOP FLOAT,
    REDUCAO_BASE FLOAT,
    FOREIGN KEY (ID_GRUPO_IMPOSTO) REFERENCES GRUPO_IMPOSTOS(ID)
);

CREATE TABLE DESPESA (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TIPO VARCHAR(50),
    VALOR FLOAT
);

CREATE TABLE FORNECEDOR (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME VARCHAR(100)
);

CREATE TABLE CUSTO (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FK_FORNECEDOR INTEGER,
    CUSTOUNITARIO FLOAT,
    CUSTOTOTAL FLOAT,
    FOREIGN KEY (FK_FORNECEDOR) REFERENCES FORNECEDOR(ID)
);

CREATE TABLE CAIXA (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    VALOR FLOAT,
    TIPO VARCHAR(20)
);

CREATE TABLE ATRIBUTO (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    IMPOSTOFEDERAL FLOAT,
    IMPOSTOESTADUAL FLOAT,
    IMPOSTOMUNICIPAL FLOAT
);

CREATE TABLE ALERTAESTOQUE (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    VALOR VARCHAR(20),
    TEMPOESTOQUE VARCHAR(20)
);

-- Tabelas do sistema PDV

CREATE TABLE VENDA_PDV (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NUMERO_CUPOM VARCHAR(20) UNIQUE NOT NULL,
    FK_CLIENTE INTEGER,
    FK_OPERADOR INTEGER NOT NULL,
    FK_TERMINAL INTEGER NOT NULL,
    DATA_VENDA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    VALOR_TOTAL DECIMAL(10,2) NOT NULL,
    VALOR_DESPESA DECIMAL(10,2) DEFAULT 0,
    VALOR_DESCONTO DECIMAL(10,2) DEFAULT 0,
    VALOR_FINAL DECIMAL(10,2) NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'CONCLUIDA',
    OBSERVACOES TEXT,
    FOREIGN KEY (FK_CLIENTE) REFERENCES USUARIO(ID),
    FOREIGN KEY (FK_OPERADOR) REFERENCES USUARIO(ID)
);

CREATE TABLE ITEM_VENDA (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FK_VENDA_PDV INTEGER NOT NULL,
    FK_PRODUTO INTEGER NOT NULL,
    QUANTIDADE INTEGER NOT NULL,
    VALOR_UNITARIO DECIMAL(10,2) NOT NULL,
    VALOR_DESCONTO DECIMAL(10,2) DEFAULT 0,
    VALOR_FINAL DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (FK_VENDA_PDV) REFERENCES VENDA_PDV(ID),
    FOREIGN KEY (FK_PRODUTO) REFERENCES PRODUTO(ID)
);

CREATE TABLE PAGAMENTO (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FK_VENDA_PDV INTEGER NOT NULL,
    TIPO_PAGAMENTO VARCHAR(20) NOT NULL,
    VALOR_PAGO DECIMAL(10,2) NOT NULL,
    VALOR_TROCO DECIMAL(10,2) DEFAULT 0,
    DATA_PAGAMENTO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    STATUS VARCHAR(20) DEFAULT 'APROVADO',
    BANDEIRA_CARTAO VARCHAR(20),
    NUMERO_PARCELAS INTEGER DEFAULT 1,
    CHAVE_PIX VARCHAR(100),
    OBSERVACOES TEXT,
    FOREIGN KEY (FK_VENDA_PDV) REFERENCES VENDA_PDV(ID)
);

CREATE TABLE CARRINHO_COMPRA (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FK_SESSAO VARCHAR(50) NOT NULL,
    FK_PRODUTO INTEGER NOT NULL,
    FK_CLIENTE INTEGER,
    FK_OPERADOR INTEGER NOT NULL,
    QUANTIDADE INTEGER NOT NULL,
    VALOR_UNITARIO DECIMAL(10,2) NOT NULL,
    VALOR_DESCONTO DECIMAL(10,2) DEFAULT 0,
    VALOR_FINAL DECIMAL(10,2) NOT NULL,
    DATA_INCLUSAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (FK_PRODUTO) REFERENCES PRODUTO(ID),
    FOREIGN KEY (FK_CLIENTE) REFERENCES USUARIO(ID),
    FOREIGN KEY (FK_OPERADOR) REFERENCES USUARIO(ID)
);

CREATE TABLE SESSAO_PDV (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FK_OPERADOR INTEGER NOT NULL,
    FK_TERMINAL INTEGER NOT NULL,
    DATA_ABERTURA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATA_FECHAMENTO TIMESTAMP,
    VALOR_ABERTURA DECIMAL(10,2) DEFAULT 0,
    VALOR_FECHAMENTO DECIMAL(10,2),
    STATUS VARCHAR(20) DEFAULT 'ABERTA',
    OBSERVACOES TEXT,
    FOREIGN KEY (FK_OPERADOR) REFERENCES USUARIO(ID)
);

CREATE TABLE CUPOM_FISCAL (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FK_VENDA_PDV INTEGER NOT NULL,
    NUMERO_CUPOM VARCHAR(20) UNIQUE NOT NULL,
    CHAVE_ACESSO VARCHAR(44),
    PROTOCOLO_AUTORIZACAO VARCHAR(15),
    DATA_EMISSAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    STATUS VARCHAR(20) DEFAULT 'EMITIDO',
    XML_CUPOM TEXT,
    PDF_CUPOM TEXT,
    FOREIGN KEY (FK_VENDA_PDV) REFERENCES VENDA_PDV(ID)
);

CREATE TABLE CONFIG_PDV (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CHAVE VARCHAR(50) UNIQUE NOT NULL,
    VALOR TEXT,
    DESCRICAO VARCHAR(255),
    TIPO VARCHAR(20) DEFAULT 'STRING',
    ATIVO BOOLEAN DEFAULT TRUE
);

-- Índices para performance
CREATE INDEX IDX_USUARIO_NOME ON USUARIO(NOME);
CREATE INDEX IDX_USUARIO_CPF ON USUARIO(CPF);
CREATE INDEX IDX_USUARIO_CNPJ ON USUARIO(CNPJ);
CREATE INDEX IDX_USUARIO_TIPO ON USUARIO(TIPO_USUARIO);
CREATE INDEX IDX_VENDA_DATA ON VENDA_PDV(DATA_VENDA);
CREATE INDEX IDX_VENDA_OPERADOR ON VENDA_PDV(FK_OPERADOR);
CREATE INDEX IDX_VENDA_STATUS ON VENDA_PDV(STATUS);
CREATE INDEX IDX_ITEM_VENDA_VENDA ON ITEM_VENDA(FK_VENDA_PDV);
CREATE INDEX IDX_ITEM_VENDA_PRODUTO ON ITEM_VENDA(FK_PRODUTO);
CREATE INDEX IDX_PAGAMENTO_VENDA ON PAGAMENTO(FK_VENDA_PDV);
CREATE INDEX IDX_PAGAMENTO_TIPO ON PAGAMENTO(TIPO_PAGAMENTO);
CREATE INDEX IDX_CARRINHO_SESSAO ON CARRINHO_COMPRA(FK_SESSAO);
CREATE INDEX IDX_PRODUTO_NOME ON PRODUTO(NOME);
CREATE INDEX IDX_PRODUTO_CODIGO ON PRODUTO(CODIGO);
CREATE INDEX IDX_PRODUTO_CODIGO_BARRAS ON PRODUTO(CODIGO_BARRAS);

-- Inserção de configurações padrão
INSERT INTO CONFIG_PDV (CHAVE, VALOR, DESCRICAO, TIPO) VALUES
('PDV_TERMINAL_NUMERO', '001', 'Número do terminal PDV', 'STRING'),
('PDV_IMPRIMIR_CUPOM', 'TRUE', 'Imprimir cupom fiscal automaticamente', 'BOOLEAN'),
('PDV_QTD_ITENS_PAGINA', '20', 'Quantidade de itens por página nos relatórios', 'NUMBER'),
('PDV_TEMPO_INATIVIDADE', '300', 'Tempo de inatividade em segundos', 'NUMBER'),
('PDV_MODO_DEBUG', 'FALSE', 'Modo debug para impressão', 'BOOLEAN'),
('PDV_CHAVE_PIX_PADRAO', 'chave@pix.com.br', 'Chave PIX padrão da empresa', 'STRING'),
('PDV_BANCO_DADOS', 'Banco do Brasil', 'Banco para transferências', 'STRING'),
('PDV_AGENCIA', '1234-5', 'Agência bancária', 'STRING'),
('PDV_CONTA', '12345-6', 'Conta bancária', 'STRING'),
('PDV_CNPJ_EMPRESA', '12.345.678/0001-95', 'CNPJ da empresa', 'STRING');

-- Log da migração
INSERT INTO CONFIG_PDV (CHAVE, VALOR, DESCRICAO, TIPO) VALUES
('MIGRATION_V1_EXECUTADA', 'TRUE', 'Script V1 de criação executado com sucesso', 'BOOLEAN');

COMMIT;
