CREATE TABLE USUARIO (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME VARCHAR(50),
    ENDERECO VARCHAR(100),
    BAIRRO VARCHAR(50),
    CIDADE VARCHAR(50),
    ESTADO VARCHAR(2),
    CEP VARCHAR(10),
    CNPJ VARCHAR(20),
    CPF VARCHAR(14),
    TIPODOCUMENTO VARCHAR(20),
    EMAIL VARCHAR(100),
    TIPOUSUARIO VARCHAR(20)
);

CREATE TABLE GRUPO_IMPOSTOS(
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME_GRUPO VARCHAR(100),
    DESCRICAO VARCHAR(255),
    ATIVO BOOLEAN,
    DATA_CRIACAO VARCHAR(20)
);

CREATE TABLE PRODUTO (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME VARCHAR(50),
    CATEGORIA VARCHAR(50),
    SUBCATEGORIA VARCHAR(50),
    CODIGO VARCHAR(50),
    MARCA VARCHAR(50),
    DATACOMPRA DATE,
    ID_GRUPO_IMPOSTO INT,
    FOREIGN KEY (ID_GRUPO_IMPOSTO) REFERENCES GRUPO_IMPOSTOS(ID)
);

CREATE TABLE ESTOQUE (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FK_PRODUTO INTEGER,
    QUANTIDADE INTEGER,
    MAXIMO INTEGER,
    MINIMO INTEGER,
    FOREIGN KEY (FK_PRODUTO) REFERENCES PRODUTO(ID)
);

CREATE TABLE LOGIN (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FK_USUARIO INTEGER,
    LOGIN VARCHAR(50),
    SENHA VARCHAR(50),
    FOREIGN KEY (FK_USUARIO) REFERENCES USUARIO(ID)
);

CREATE TABLE IMPOSTO (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_GRUPO_IMPOSTO INT,
    ORIGEM_MERCADORIA FLOAT,
    CST_ICMS VARCHAR(10),
    CSOSN VARCHAR(10),
    ALIQUOTA_ICMS FLOAT,
    ALIQUOTA_COFINS FLOAT,
    ALIQUOTA_IPI FLOAT,
    CFOP FLOAT,
    REDUCAO_BASE FLOAT,
    FOREIGN KEY (ID_GRUPO_IMPOSTO) REFERENCES GRUPO_IMPOSTOS(ID)
);

CREATE TABLE DESPESA (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TIPO VARCHAR(50),
    VALOR FLOAT
);

CREATE TABLE FORNECEDOR (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME VARCHAR(100)
);

CREATE TABLE CUSTO (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    FK_FORNECEDOR INTEGER,
    CUSTOUNITARIO FLOAT,
    CUSTOTOTAL FLOAT,
    FOREIGN KEY (FK_FORNECEDOR) REFERENCES FORNECEDOR(ID)
);

CREATE TABLE CAIXA (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    VALORCAIXA FLOAT,
    VALOR FLOAT,
    TIPO VARCHAR(20)
);

CREATE TABLE ATRIBUTO (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    IMPOSTOFEDERAL FLOAT,
    IMPOSTOESTADUAL FLOAT,
    IMPOSTOMUNICIPAL FLOAT
);

CREATE TABLE ALERTAESTOQUE (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    VALOR VARCHAR(20),
    TEMPOESTOQUE VARCHAR(20)
);
