create table itemvenda(
     id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
     fk_produto int,
     quantidade int,
     FOREIGN KEY (fk_produto) REFERENCES produto(id)
);

ALTER TABLE estoque ADD COLUMN lote VARCHAR(20), ADD COLUMN dtVencimento VARCHAR(10);
ALTER TABLE estoque
ADD CONSTRAINT fk_produto_estoque
FOREIGN KEY (fk_produto)
REFERENCES produto (id);

--ALTER TABLE CUSTO RENAME TO VENDA;
--ALTER TABLE VENDA RENAME COLUMN CUSTOUNITARIO TO PRECOCUSTO;
--ALTER TABLE VENDA RENAME COLUMN CUSTOTOTAL TO CUSTOVENDA;
ALTER TABLE VENDA ADD COLUMN UNIDADE VARCHAR(10), ADD COLUMN QTDMINIMA VARCHAR(10), ADD COLUMN MARGEMLUCRO INTEGER;

ALTER TABLE USUARIO ADD COLUMN TIPODOCUMENTO VARCHAR(14);