-- V2__update_comercialHermesDB.sql
-- Script de migração para atualizar o banco de dados existente
-- Data: 2024-04-17
-- Autor: Sistema Hermes Comercial

-- Adicionar colunas que podem estar faltando na tabela PRODUTO
ALTER TABLE PRODUTO ADD COLUMN IF NOT EXISTS CODIGO_BARRAS VARCHAR(20);
ALTER TABLE PRODUTO ADD COLUMN IF NOT EXISTS PRECO_VENDA DECIMAL(10,2);
ALTER TABLE PRODUTO ADD COLUMN IF NOT EXISTS PRECO_CUSTO DECIMAL(10,2);
ALTER TABLE PRODUTO ADD COLUMN IF NOT EXISTS UNIDADE VARCHAR(10);

-- Adicionar coluna PIS na tabela IMPOSTO se não existir
ALTER TABLE IMPOSTO ADD COLUMN IF NOT EXISTS ALIQUOTA_PIS FLOAT;

-- Atualizar dados existentes se necessário
UPDATE PRODUTO SET UNIDADE = 'UN' WHERE UNIDADE IS NULL;
UPDATE PRODUTO SET PRECO_VENDA = 0.00 WHERE PRECO_VENDA IS NULL;
UPDATE PRODUTO SET PRECO_CUSTO = 0.00 WHERE PRECO_CUSTO IS NULL;

-- Adicionar colunas na tabela ESTOQUE se não existirem
ALTER TABLE ESTOQUE ADD COLUMN IF NOT EXISTS LOTE VARCHAR(20);
ALTER TABLE ESTOQUE ADD COLUMN IF NOT EXISTS DATA_VENCIMENTO DATE;

-- Log da migração
INSERT INTO CONFIG_PDV (CHAVE, VALOR, DESCRICAO, TIPO) VALUES
('MIGRATION_V2_EXECUTADA', 'TRUE', 'Script V2 de atualização executado com sucesso', 'BOOLEAN');

COMMIT;
