ALTER TABLE CUSTO RENAME TO VENDA;
ALTER TABLE VENDA RENAME COLUMN CUSTOUNITARIO TO PRECOCUSTO;
ALTER TABLE VENDA RENAME COLUMN CUSTOTOTAL TO CUSTOVENDA;
ALTER TABLE VENDA ADD COLUMN UNIDADE VARCHAR(10), ADD COLUMN QTDMINIMA VARCHAR(10), ADD COLUMN MARGEMLUCRO INTEGER;